export const ADD_INGREDIENT = 'ADDINGREDIENT'
export const REMOVE_INGREDIENT = 'REMOVEINGREDIENT'
export const SET_INGREDIENT = 'SET_INGREDIENT'
export const FECTH_INGREDIENT_FAIL = 'FETCH_INGREDIENT_FAIL'


export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCESS'
export const PURCHASE_BURGER_FAIL = 'PURCHASE_BURGER_FAIL'
export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START'
export const PURCHASE_INIT = 'PURCHASE_INIT';

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';


export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH'